const PDFDocument = require("pdfkit");

// Streams a PDF report directly to the response. Kept server-side so the
// report is generated consistently regardless of the client's browser/fonts.
function generateReportPDF(res, { score, band, byScenario, events, legalFacts }) {
  const doc = new PDFDocument({ margin: 50 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=digital-risk-report.pdf"
  );
  doc.pipe(res);

  doc
    .fontSize(20)
    .text("Digital Risk Awareness Report", { align: "left" })
    .moveDown(0.5);

  doc
    .fontSize(11)
    .fillColor("#555555")
    .text("Generated by the Awareness Simulator — for educational use.")
    .moveDown(1);

  doc
    .fontSize(14)
    .fillColor("#000000")
    .text(`Risk Score: ${score} / 100  —  ${band}`)
    .moveDown(1);

  doc.fontSize(13).text("Breakdown by scenario:").moveDown(0.3);
  Object.entries(byScenario).forEach(([scenario, raw]) => {
    doc.fontSize(11).text(`  • ${scenario}: raw risk points ${raw}`);
  });
  doc.moveDown(1);

  doc.fontSize(13).text("Choices made during this session:").moveDown(0.3);
  events.forEach((e) => {
    doc
      .fontSize(10)
      .fillColor("#333333")
      .text(`  • [${e.scenario}] ${e.action}`);
  });
  doc.moveDown(1);

  if (legalFacts && legalFacts.length) {
    doc.fontSize(13).fillColor("#000000").text("What to do / know:").moveDown(0.3);
    legalFacts.forEach((f) => {
      doc.fontSize(11).fillColor("#000000").text(f.title, { continued: false });
      doc.fontSize(9).fillColor("#555555").text(f.summary);
      doc.fontSize(8).fillColor("#888888").text(`Source: ${f.source}`).moveDown(0.5);
    });
  }

  doc.moveDown(1);
  doc
    .fontSize(9)
    .fillColor("#888888")
    .text(
      "If you believe you have experienced real harm from any of these scenarios, " +
        "report it at cybercrime.gov.in or call the national helpline at 1930."
    );

  doc.end();
}

module.exports = generateReportPDF;
